# Generated by Django 4.0.4 on 2022-05-18 04:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('release_year', models.IntegerField()),
                ('average', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
